spring:
  cloud:
    gateway:
      routes:
        - id : r1
          uri:
              http://localhost:7070/
          predicates:
            - Path=/etudiants/**
        - id: r2
          uri:
              http://localhost:7071/
          predicates:
            - Path=/unites/**